# fly.toml app configuration file generated for gymlog-api-purple-pond-6642 on 2024-10-03T00:25:44-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gymlog-api-purple-pond-6642'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256MB'
  cpu_kind = 'shared'
  cpus = 1
